server:
  port: 8081
  servlet:
    context-path: /resource-server
  tomcat:
    max-swallow-size: 90MB
    connection-timeout: 120s
####### resource server configuration properties
spring:
  mvc:
    async:
      request-timeout: -1
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8083/auth/realms/baeldung
          jwk-set-uri: http://localhost:8083/auth/realms/baeldung/protocol/openid-connect/certs
  servlet:
    multipart:
      max-file-size: 90MB
      max-request-size: 90MB
  sleuth:
    enabled: true
    async:
      enabled: false
logging:
  level:
    root: DEBUG
    org:
          springframework:
            web: debug
          hibernate:
            internal:
              util: INFO
          apache:
            coyote:
              http11:
                Http11InputBuffer: OFF
######################### my variables #######################################
NUM_THREADS: 4
REQ_PARALLEL: 2
base_fe_url: http://localhost:8089/
realm: baeldung
