server:
  port: 8081
  servlet:
    context-path: /resource-server
  tomcat:
    max-swallow-size: 90MB
    connection-timeout: 120s
####### resource server configuration properties
spring:
  mvc:
    async:
      request-timeout: -1
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8083/auth/realms/baeldung
          jwk-set-uri: http://localhost:8083/auth/realms/baeldung/protocol/openid-connect/certs
  servlet:
    multipart:
      max-file-size: 90MB
      max-request-size: 90MB
  datasource:
    url: jdbc:mysql://localhost:3306/IMAGE
    username: admin
    password: password
    driver-class-name: com.mysql.jdbc.Driver
  jpa:
    database-platform: org.hibernate.dialect.MySQL57InnoDBDialect
    hibernate:
      ddl-auto: create
hibernate:
  connection:
    provider_class: org.hibernate.connection.C3P0ConnectionProvider
logging:
  level:
    root: DEBUG
    org:
          springframework:
            web: debug
######################### my variables #######################################
NUM_THREADS: 4
base_fe_url: http://localhost:8089/
